server:
  port: 8090
  wait-time-in-ms-when-sync-empty: 5  # ??? ??? ?? ? ??? ?? ??(ms) : ?? ?? ?? (default 5? : ????? ?? ???? ?? ?? ???? ?? 5? ? ??? ??)


spring:
  application:
    name: service-discovery

eureka:
  client:
    register-with-eureka: false # ??? ???? (???) ?? ??
    fetch-registry: false  # (??? ????? ??) ?? ????? ??? fetch ??
  server:
    enable-self-preservation: true
    instance:
      lease-renewal-internal-in-seconds: 30
      lease-expiration-duration-in-seconds: 90


#serviceUrl:
#     defaultZone: http://localhost:8090/eureka/ # ??? ?? ??? ?? http://localhost:8090/ ? ????.

#    server:
#        wait-time-in-ms-when-sync-empty: 5  # ??? ??? ?? ? ??? ?? ??(ms) : ?? ?? ?? (default 5? : ????? ?? ???? ?? ?? ???? ?? 5? ? ??? ??)

#management:
 # endpoints:
  #  web:
   #   exposure:
    #    include: "*"
